#pragma once

/*
 * C-compatible bootstrap values needed before the C++ Flash configuration
 * runner starts.  Runtime settings replace these immediately after startup.
 */
#define PRINDOG_FACTORY_BOARD_ID 1U

#define PRINDOG_FACTORY_IP0 192U
#define PRINDOG_FACTORY_IP1 168U
#define PRINDOG_FACTORY_IP2 100U
#define PRINDOG_FACTORY_IP3 102U

#define PRINDOG_FACTORY_NETMASK0 255U
#define PRINDOG_FACTORY_NETMASK1 255U
#define PRINDOG_FACTORY_NETMASK2 255U
#define PRINDOG_FACTORY_NETMASK3 0U

#define PRINDOG_FACTORY_GATEWAY0 192U
#define PRINDOG_FACTORY_GATEWAY1 168U
#define PRINDOG_FACTORY_GATEWAY2 100U
#define PRINDOG_FACTORY_GATEWAY3 100U

#define PRINDOG_FACTORY_MASTER0 192U
#define PRINDOG_FACTORY_MASTER1 168U
#define PRINDOG_FACTORY_MASTER2 100U
#define PRINDOG_FACTORY_MASTER3 100U

#define PRINDOG_FACTORY_MAC0 0x02U
#define PRINDOG_FACTORY_MAC1 0x80U
#define PRINDOG_FACTORY_MAC2 0xE1U
#define PRINDOG_FACTORY_MAC3 0x00U
#define PRINDOG_FACTORY_MAC4 0x00U
#define PRINDOG_FACTORY_MAC5 0x02U

#define PRINDOG_FACTORY_LOCAL_UDP_PORT 5005U
#define PRINDOG_FACTORY_MASTER_UDP_PORT 5006U
